LobbyWorld: "world"

Spawn:
  World: world
  X: 0
  Y: 0
  Z: 0
  Yaw: 0
  Pitch: 0
  Set: false

Items:
  Games: true
  Profile: true
  Cosmetics: true
  Settings: true

Scoreboard:
  Enabled: true
  Title: "&a&lJadedMC"
  Lines:
    - "&7%localtime_time_MM/dd/YY%"
    - "&aRank:"
    - "  %jadedcore_rank_displayname_legacy%"
    - ""
    - "&aParkour:"
    - "  %ajpk_stats_highscore%"
    - ""
    - ""
    - "&aOnline:"
    - "  %bungee_total%"
    - ""
    - "&aplay.jadedmc.net"