name: JadedLobby
version: '${project.version}'
main: net.jadedmc.jadedlobby.JadedLobbyPlugin
api-version: "1.19"

depend:
  - PlaceholderAPI
  - Votifier

commands:
  jamison:
    description: Open jamison the journeymen.
  spawn:
    description: spawn command
  setspawn:
    description: set spawn command.
  vote:
    description: View vote links.