name: JadedLobby
version: '${project.version}'
main: net.jadedmc.jadedlobby.JadedLobbyPlugin
api-version: "1.19"

depend:
  - PlaceholderAPI
  - Votifier

commands:
  spawn:
    description: spawn command
  setspawn:
    description: set spawn command.